# Configuración de la Aplicación
spring.application.name=system

# Configuración de la Base de Datos (Render)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d851nr0js32c73a6a5rg-a.oregon-postgres.render.com:5432/prueba_universidad?sslmode=require
spring.datasource.username=prueba_universidad_user
spring.datasource.password=ujvZaPYaVyjCy5a1ephsjuBQgUjaKa4n

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true