# Configuración de la Aplicación
spring.application.name=system
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://ep-little-glitter-apvqc7l8.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_V1aWcAPd9xi

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d851nr0js32c73a6a5rg-a.oregon-postgres.render.com:5432/prueba_universidad?sslmode=require
spring.datasource.username=prueba_universidad_user
spring.datasource.password=ujvZaPYaVyjCy5a1ephsjuBQgUjaKa4n



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true